const { jsPDF } = require('jspdf');
require('jspdf-autotable');

/**
 * Generate seating chart PDF for an exam
 */
function generateSeatingChartPDF(exam, allotments, rooms) {
  const doc = new jsPDF('l', 'mm', 'a4');
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(30, 58, 138);
  doc.text('HallEase - Seating Chart', 14, 20);
  
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`${exam.title} | ${exam.subject}`, 14, 28);
  doc.text(`${exam.department} - Semester ${exam.semester} | ${new Date(exam.examDate).toLocaleDateString()}`, 14, 34);
  
  // Table data
  const tableData = allotments.map((a, i) => [
    i + 1,
    a.studentId?.rollNo || '-',
    a.studentId?.name || '-',
    a.studentId?.department || '-',
    `Sem ${a.studentId?.semester || '-'}`,
    a.roomId?.roomNo || '-',
    a.seatNo,
    a.studentId?.accommodations?.wheelchair ? 'PWD' : '-'
  ]);
  
  doc.autoTable({
    head: [['#', 'Roll No', 'Name', 'Department', 'Class', 'Hall', 'Seat', 'Notes']],
    body: tableData,
    startY: 42,
    styles: { fontSize: 9, cellPadding: 2 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 8 },
      6: { cellWidth: 15, fontStyle: 'bold' }
    }
  });
  
  // Room summary
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(11);
  doc.setTextColor(30, 58, 138);
  doc.text('Room Summary', 14, finalY);
  
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  let yPos = finalY + 7;
  rooms.forEach(room => {
    const count = allotments.filter(a => a.roomId?._id?.toString() === room._id.toString()).length;
    doc.text(`${room.roomNo}: ${count} students | Capacity: ${room.capacity} | Layout: ${room.rows}×${room.cols}`, 14, yPos);
    yPos += 5;
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by HallEase on ${new Date().toLocaleString()}`, 14, 195);
  
  return doc.output('buffer');
}

/**
 * Generate individual hall ticket PDF
 */
function generateHallTicketPDF(student, exam, allotment) {
  const doc = new jsPDF('p', 'mm', [80, 120]); // ID card size
  
  // Header
  doc.setFillColor(30, 58, 138);
  doc.rect(0, 0, 80, 20, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.text('HallEase', 40, 10, { align: 'center' });
  doc.setFontSize(8);
  doc.text('Exam Hall Ticket', 40, 16, { align: 'center' });
  
  // Student info
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(9);
  doc.text(student.name, 40, 28, { align: 'center' });
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(`Roll: ${student.rollNo}`, 40, 33, { align: 'center' });
  doc.text(`${student.department} | Sem ${student.semester}`, 40, 38, { align: 'center' });
  
  // Exam info
  doc.setDrawColor(200, 200, 200);
  doc.line(10, 43, 70, 43);
  
  doc.setTextColor(30, 58, 138);
  doc.setFontSize(8);
  doc.text(exam.title, 40, 49, { align: 'center' });
  doc.setFontSize(7);
  doc.setTextColor(80, 80, 80);
  doc.text(exam.subject, 40, 53, { align: 'center' });
  doc.text(`${new Date(exam.examDate).toLocaleDateString()} | ${exam.startTime}`, 40, 57, { align: 'center' });
  
  // Seat highlight
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(15, 62, 50, 22, 3, 3, 'F');
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(7);
  doc.text('HALL', 40, 68, { align: 'center' });
  doc.text('SEAT', 40, 80, { align: 'center' });
  doc.setTextColor(30, 58, 138);
  doc.setFontSize(12);
  doc.text(allotment.roomId?.roomNo || '-', 40, 75, { align: 'center' });
  doc.setFontSize(14);
  doc.text(allotment.seatNo, 40, 87, { align: 'center' });
  
  // QR placeholder
  doc.setDrawColor(200, 200, 200);
  doc.roundedRect(25, 90, 30, 30, 2, 2, 'D');
  doc.setFontSize(6);
  doc.setTextColor(150, 150, 150);
  doc.text('Scan for verification', 40, 108, { align: 'center' });
  
  // Footer
  doc.setFontSize(5);
  doc.text('Valid ID required | Reach 30 min early', 40, 116, { align: 'center' });
  
  return doc.output('buffer');
}

module.exports = {
  generateSeatingChartPDF,
  generateHallTicketPDF
};
